### PR TITLE
Add *option* to allow self-signed certificates, ref #14

### PR DESCRIPTION
**Pull request by michielbdejong**
This leaves the default behavior safe, but allows overriding it.

Haven't tested this yet!

### CODE REVIEW

**Comment by michielbdejong** [comment]
Tested and confirms that it switches the `rejectUnauthorized` field from true to false.

@Gara64 let me know if with this (checking the 'Allow self-signed certificates' box on the web form) it still doesn't work for your ownCloud server.

**Comment by paultranvan** [comment]
Oddly, when `rejectUnauthorized` is explicity set at true, the default example owncloud.michielbdejong.com doesn't work anymore; an error UNABLE_TO_VERIFY_LEAF_SIGNATURE is received. Do you have the same behaviour? 
When it is set at false, it works with your server and mine. I Still have the #15 issue, though

**Comment by michielbdejong** [comment]
> Oddly, when rejectUnauthorized is explicity set at true, the default example owncloud.michielbdejong.com doesn't work anymore 

That is indeed very odd, and I indeed found the same thing, and changed it to leave it unset if you don't check the checkbox. This looks like a bug in the ssl-root-cas package, will investigate further.

**Comment by michielbdejong** [comment]
@Gara64 should now be fixed by df9aafb - I deployed it to https://server-to-server.michielbdejong.com:8123/, please test there!

**Comment by michielbdejong** [comment]
For reference, I reported the odd behavior regarding explicit `rejectUnauthorized: true`, [here](https://github.com/coolaj86/node-ssl-root-cas/pull/16)

**Pull request closed without merging**
